-- Joueurs réels et clubs réels — positions/nationalités publiques.
-- Les champs optionnels date_naissance, pied_fort, taille et poids restent NULL pour éviter des valeurs non vérifiées.
BEGIN;
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (1, 'Becker', 'Alisson', NULL, 'Brésil', 'Gardien', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (2, 'Mamardashvili', 'Giorgi', NULL, 'Géorgie', 'Gardien', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (3, 'van Dijk', 'Virgil', NULL, 'Pays-Bas', 'Défenseur', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (4, 'Frimpong', 'Jeremie', NULL, 'Pays-Bas', 'Défenseur', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (5, 'Kerkez', 'Milos', NULL, 'Hongrie', 'Défenseur', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (6, 'Mac Allister', 'Alexis', NULL, 'Argentine', 'Milieu', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (7, 'Wirtz', 'Florian', NULL, 'Allemagne', 'Milieu', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (8, 'Isak', 'Alexander', NULL, 'Suède', 'Attaquant', NULL, NULL, NULL, 1);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (9, 'Sánchez', 'Robert', NULL, 'Espagne', 'Gardien', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (10, 'James', 'Reece', NULL, 'Angleterre', 'Défenseur', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (11, 'Chalobah', 'Trevoh', NULL, 'Angleterre', 'Défenseur', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (12, 'Gusto', 'Malo', NULL, 'France', 'Défenseur', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (13, 'Caicedo', 'Moisés', NULL, 'Équateur', 'Milieu', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (14, 'Fernández', 'Enzo', NULL, 'Argentine', 'Milieu', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (15, 'Palmer', 'Cole', NULL, 'Angleterre', 'Milieu', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (16, 'Pedro', 'João', NULL, 'Brésil', 'Attaquant', NULL, NULL, NULL, 2);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (17, 'Donnarumma', 'Gianluigi', NULL, 'Italie', 'Gardien', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (18, 'Dias', 'Rúben', NULL, 'Portugal', 'Défenseur', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (19, 'Gvardiol', 'Joško', NULL, 'Croatie', 'Défenseur', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (20, 'Hernández', 'Rodri', NULL, 'Espagne', 'Milieu', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (21, 'Reijnders', 'Tijjani', NULL, 'Pays-Bas', 'Milieu', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (22, 'Foden', 'Phil', NULL, 'Angleterre', 'Milieu', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (23, 'Cherki', 'Rayan', NULL, 'France', 'Milieu', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (24, 'Haaland', 'Erling', NULL, 'Norvège', 'Attaquant', NULL, NULL, NULL, 3);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (25, 'Courtois', 'Thibaut', NULL, 'Belgique', 'Gardien', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (26, 'Konaté', 'Ibrahima', NULL, 'France', 'Défenseur', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (27, 'Cucurella', 'Marc', NULL, 'Espagne', 'Défenseur', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (28, 'Bellingham', 'Jude', NULL, 'Angleterre', 'Milieu', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (29, 'Valverde', 'Federico', NULL, 'Uruguay', 'Milieu', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (30, 'Güler', 'Arda', NULL, 'Turquie', 'Milieu', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (31, 'Júnior', 'Vinícius', NULL, 'Brésil', 'Attaquant', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (32, 'Mbappé', 'Kylian', NULL, 'France', 'Attaquant', NULL, NULL, NULL, 4);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (33, 'García', 'Joan', NULL, 'Espagne', 'Gardien', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (34, 'Cubarsí', 'Pau', NULL, 'Espagne', 'Défenseur', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (35, 'Koundé', 'Jules', NULL, 'France', 'Défenseur', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (36, 'González', 'Pedri', NULL, 'Espagne', 'Milieu', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (37, 'Páez', 'Gavi', NULL, 'Espagne', 'Milieu', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (38, 'Olmo', 'Dani', NULL, 'Espagne', 'Milieu', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (39, 'Nasraoui', 'Lamine Yamal', NULL, 'Espagne', 'Attaquant', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (40, 'Belloli', 'Raphinha', NULL, 'Brésil', 'Attaquant', NULL, NULL, NULL, 5);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (41, 'Neuer', 'Manuel', NULL, 'Allemagne', 'Gardien', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (42, 'Upamecano', 'Dayot', NULL, 'France', 'Défenseur', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (43, 'Tah', 'Jonathan', NULL, 'Allemagne', 'Défenseur', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (44, 'Kimmich', 'Joshua', NULL, 'Allemagne', 'Milieu', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (45, 'Musiala', 'Jamal', NULL, 'Allemagne', 'Milieu', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (46, 'Díaz', 'Luis', NULL, 'Colombie', 'Attaquant', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (47, 'Olise', 'Michael', NULL, 'France', 'Attaquant', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (48, 'Kane', 'Harry', NULL, 'Angleterre', 'Attaquant', NULL, NULL, NULL, 6);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (49, 'Chevalier', 'Lucas', NULL, 'France', 'Gardien', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (50, 'Hakimi', 'Achraf', NULL, 'Maroc', 'Défenseur', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (51, 'Marquinhos', 'Marcos', NULL, 'Brésil', 'Défenseur', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (52, 'Mendes', 'Nuno', NULL, 'Portugal', 'Défenseur', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (53, 'Ferreira', 'Vitinha', NULL, 'Portugal', 'Milieu', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (54, 'Neves', 'João', NULL, 'Portugal', 'Milieu', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (55, 'Kvaratskhelia', 'Khvicha', NULL, 'Géorgie', 'Attaquant', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (56, 'Dembélé', 'Ousmane', NULL, 'France', 'Attaquant', NULL, NULL, NULL, 7);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (57, 'Martínez', 'Lautaro', NULL, 'Argentine', 'Attaquant', NULL, NULL, NULL, 8);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (58, 'Thuram', 'Marcus', NULL, 'France', 'Attaquant', NULL, NULL, NULL, 8);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (59, 'Akanji', 'Manuel', NULL, 'Suisse', 'Défenseur', NULL, NULL, NULL, 8);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (60, 'Dumfries', 'Denzel', NULL, 'Pays-Bas', 'Défenseur', NULL, NULL, NULL, 8);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (61, 'Çalhanoğlu', 'Hakan', NULL, 'Turquie', 'Milieu', NULL, NULL, NULL, 8);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (62, 'Sučić', 'Petar', NULL, 'Croatie', 'Milieu', NULL, NULL, NULL, 8);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (63, 'Esposito', 'Francesco Pio', NULL, 'Italie', 'Attaquant', NULL, NULL, NULL, 8);
INSERT INTO joueur (id, nom, prenom, date_naissance, nationalite, poste_principal, pied_fort, taille, poids, club_id) VALUES (64, 'Zieliński', 'Piotr', NULL, 'Pologne', 'Milieu', NULL, NULL, NULL, 8);
SELECT setval(pg_get_serial_sequence('joueur','id'), (SELECT MAX(id) FROM joueur));
COMMIT;
