-- Notes SYNTHÉTIQUES de 0 à 100. Elles servent uniquement aux tests CRUD, filtres et futur RAG.
BEGIN;
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (1, 1, 'Réflexes', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (2, 1, 'Prise de balle', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (3, 1, 'Jeu aérien', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (4, 1, 'Jeu au pied', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (5, 1, 'Positionnement', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (6, 1, 'Relance', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (7, 2, 'Réflexes', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (8, 2, 'Prise de balle', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (9, 2, 'Jeu aérien', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (10, 2, 'Jeu au pied', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (11, 2, 'Positionnement', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (12, 2, 'Relance', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (13, 3, 'Duel défensif', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (14, 3, 'Placement', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (15, 3, 'Vitesse', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (16, 3, 'Relance', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (17, 3, 'Jeu aérien', 72);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (18, 3, 'Anticipation', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (19, 4, 'Duel défensif', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (20, 4, 'Placement', 72);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (21, 4, 'Vitesse', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (22, 4, 'Relance', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (23, 4, 'Jeu aérien', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (24, 4, 'Anticipation', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (25, 5, 'Duel défensif', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (26, 5, 'Placement', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (27, 5, 'Vitesse', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (28, 5, 'Relance', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (29, 5, 'Jeu aérien', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (30, 5, 'Anticipation', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (31, 6, 'Qualité de passe', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (32, 6, 'Vision du jeu', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (33, 6, 'Technique', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (34, 6, 'Mobilité', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (35, 6, 'Pressing', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (36, 6, 'Endurance', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (37, 7, 'Qualité de passe', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (38, 7, 'Vision du jeu', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (39, 7, 'Technique', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (40, 7, 'Mobilité', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (41, 7, 'Pressing', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (42, 7, 'Endurance', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (43, 8, 'Finition', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (44, 8, 'Appels', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (45, 8, 'Vitesse', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (46, 8, 'Technique', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (47, 8, 'Création', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (48, 8, 'Pressing', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (49, 9, 'Réflexes', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (50, 9, 'Prise de balle', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (51, 9, 'Jeu aérien', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (52, 9, 'Jeu au pied', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (53, 9, 'Positionnement', 71);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (54, 9, 'Relance', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (55, 10, 'Duel défensif', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (56, 10, 'Placement', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (57, 10, 'Vitesse', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (58, 10, 'Relance', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (59, 10, 'Jeu aérien', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (60, 10, 'Anticipation', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (61, 11, 'Duel défensif', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (62, 11, 'Placement', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (63, 11, 'Vitesse', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (64, 11, 'Relance', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (65, 11, 'Jeu aérien', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (66, 11, 'Anticipation', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (67, 12, 'Duel défensif', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (68, 12, 'Placement', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (69, 12, 'Vitesse', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (70, 12, 'Relance', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (71, 12, 'Jeu aérien', 72);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (72, 12, 'Anticipation', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (73, 13, 'Qualité de passe', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (74, 13, 'Vision du jeu', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (75, 13, 'Technique', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (76, 13, 'Mobilité', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (77, 13, 'Pressing', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (78, 13, 'Endurance', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (79, 14, 'Qualité de passe', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (80, 14, 'Vision du jeu', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (81, 14, 'Technique', 90);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (82, 14, 'Mobilité', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (83, 14, 'Pressing', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (84, 14, 'Endurance', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (85, 15, 'Qualité de passe', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (86, 15, 'Vision du jeu', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (87, 15, 'Technique', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (88, 15, 'Mobilité', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (89, 15, 'Pressing', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (90, 15, 'Endurance', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (91, 16, 'Finition', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (92, 16, 'Appels', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (93, 16, 'Vitesse', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (94, 16, 'Technique', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (95, 16, 'Création', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (96, 16, 'Pressing', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (97, 17, 'Réflexes', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (98, 17, 'Prise de balle', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (99, 17, 'Jeu aérien', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (100, 17, 'Jeu au pied', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (101, 17, 'Positionnement', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (102, 17, 'Relance', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (103, 18, 'Duel défensif', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (104, 18, 'Placement', 73);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (105, 18, 'Vitesse', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (106, 18, 'Relance', 73);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (107, 18, 'Jeu aérien', 73);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (108, 18, 'Anticipation', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (109, 19, 'Duel défensif', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (110, 19, 'Placement', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (111, 19, 'Vitesse', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (112, 19, 'Relance', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (113, 19, 'Jeu aérien', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (114, 19, 'Anticipation', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (115, 20, 'Qualité de passe', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (116, 20, 'Vision du jeu', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (117, 20, 'Technique', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (118, 20, 'Mobilité', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (119, 20, 'Pressing', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (120, 20, 'Endurance', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (121, 21, 'Qualité de passe', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (122, 21, 'Vision du jeu', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (123, 21, 'Technique', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (124, 21, 'Mobilité', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (125, 21, 'Pressing', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (126, 21, 'Endurance', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (127, 22, 'Qualité de passe', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (128, 22, 'Vision du jeu', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (129, 22, 'Technique', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (130, 22, 'Mobilité', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (131, 22, 'Pressing', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (132, 22, 'Endurance', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (133, 23, 'Qualité de passe', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (134, 23, 'Vision du jeu', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (135, 23, 'Technique', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (136, 23, 'Mobilité', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (137, 23, 'Pressing', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (138, 23, 'Endurance', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (139, 24, 'Finition', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (140, 24, 'Appels', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (141, 24, 'Vitesse', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (142, 24, 'Technique', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (143, 24, 'Création', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (144, 24, 'Pressing', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (145, 25, 'Réflexes', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (146, 25, 'Prise de balle', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (147, 25, 'Jeu aérien', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (148, 25, 'Jeu au pied', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (149, 25, 'Positionnement', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (150, 25, 'Relance', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (151, 26, 'Duel défensif', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (152, 26, 'Placement', 73);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (153, 26, 'Vitesse', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (154, 26, 'Relance', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (155, 26, 'Jeu aérien', 72);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (156, 26, 'Anticipation', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (157, 27, 'Duel défensif', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (158, 27, 'Placement', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (159, 27, 'Vitesse', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (160, 27, 'Relance', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (161, 27, 'Jeu aérien', 70);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (162, 27, 'Anticipation', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (163, 28, 'Qualité de passe', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (164, 28, 'Vision du jeu', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (165, 28, 'Technique', 90);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (166, 28, 'Mobilité', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (167, 28, 'Pressing', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (168, 28, 'Endurance', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (169, 29, 'Qualité de passe', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (170, 29, 'Vision du jeu', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (171, 29, 'Technique', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (172, 29, 'Mobilité', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (173, 29, 'Pressing', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (174, 29, 'Endurance', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (175, 30, 'Qualité de passe', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (176, 30, 'Vision du jeu', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (177, 30, 'Technique', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (178, 30, 'Mobilité', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (179, 30, 'Pressing', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (180, 30, 'Endurance', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (181, 31, 'Finition', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (182, 31, 'Appels', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (183, 31, 'Vitesse', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (184, 31, 'Technique', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (185, 31, 'Création', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (186, 31, 'Pressing', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (187, 32, 'Finition', 92);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (188, 32, 'Appels', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (189, 32, 'Vitesse', 90);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (190, 32, 'Technique', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (191, 32, 'Création', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (192, 32, 'Pressing', 91);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (193, 33, 'Réflexes', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (194, 33, 'Prise de balle', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (195, 33, 'Jeu aérien', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (196, 33, 'Jeu au pied', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (197, 33, 'Positionnement', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (198, 33, 'Relance', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (199, 34, 'Duel défensif', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (200, 34, 'Placement', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (201, 34, 'Vitesse', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (202, 34, 'Relance', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (203, 34, 'Jeu aérien', 73);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (204, 34, 'Anticipation', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (205, 35, 'Duel défensif', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (206, 35, 'Placement', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (207, 35, 'Vitesse', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (208, 35, 'Relance', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (209, 35, 'Jeu aérien', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (210, 35, 'Anticipation', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (211, 36, 'Qualité de passe', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (212, 36, 'Vision du jeu', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (213, 36, 'Technique', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (214, 36, 'Mobilité', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (215, 36, 'Pressing', 74);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (216, 36, 'Endurance', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (217, 37, 'Qualité de passe', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (218, 37, 'Vision du jeu', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (219, 37, 'Technique', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (220, 37, 'Mobilité', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (221, 37, 'Pressing', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (222, 37, 'Endurance', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (223, 38, 'Qualité de passe', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (224, 38, 'Vision du jeu', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (225, 38, 'Technique', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (226, 38, 'Mobilité', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (227, 38, 'Pressing', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (228, 38, 'Endurance', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (229, 39, 'Finition', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (230, 39, 'Appels', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (231, 39, 'Vitesse', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (232, 39, 'Technique', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (233, 39, 'Création', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (234, 39, 'Pressing', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (235, 40, 'Finition', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (236, 40, 'Appels', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (237, 40, 'Vitesse', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (238, 40, 'Technique', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (239, 40, 'Création', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (240, 40, 'Pressing', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (241, 41, 'Réflexes', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (242, 41, 'Prise de balle', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (243, 41, 'Jeu aérien', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (244, 41, 'Jeu au pied', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (245, 41, 'Positionnement', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (246, 41, 'Relance', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (247, 42, 'Duel défensif', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (248, 42, 'Placement', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (249, 42, 'Vitesse', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (250, 42, 'Relance', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (251, 42, 'Jeu aérien', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (252, 42, 'Anticipation', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (253, 43, 'Duel défensif', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (254, 43, 'Placement', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (255, 43, 'Vitesse', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (256, 43, 'Relance', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (257, 43, 'Jeu aérien', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (258, 43, 'Anticipation', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (259, 44, 'Qualité de passe', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (260, 44, 'Vision du jeu', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (261, 44, 'Technique', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (262, 44, 'Mobilité', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (263, 44, 'Pressing', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (264, 44, 'Endurance', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (265, 45, 'Qualité de passe', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (266, 45, 'Vision du jeu', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (267, 45, 'Technique', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (268, 45, 'Mobilité', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (269, 45, 'Pressing', 72);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (270, 45, 'Endurance', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (271, 46, 'Finition', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (272, 46, 'Appels', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (273, 46, 'Vitesse', 90);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (274, 46, 'Technique', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (275, 46, 'Création', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (276, 46, 'Pressing', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (277, 47, 'Finition', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (278, 47, 'Appels', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (279, 47, 'Vitesse', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (280, 47, 'Technique', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (281, 47, 'Création', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (282, 47, 'Pressing', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (283, 48, 'Finition', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (284, 48, 'Appels', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (285, 48, 'Vitesse', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (286, 48, 'Technique', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (287, 48, 'Création', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (288, 48, 'Pressing', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (289, 49, 'Réflexes', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (290, 49, 'Prise de balle', 73);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (291, 49, 'Jeu aérien', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (292, 49, 'Jeu au pied', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (293, 49, 'Positionnement', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (294, 49, 'Relance', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (295, 50, 'Duel défensif', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (296, 50, 'Placement', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (297, 50, 'Vitesse', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (298, 50, 'Relance', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (299, 50, 'Jeu aérien', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (300, 50, 'Anticipation', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (301, 51, 'Duel défensif', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (302, 51, 'Placement', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (303, 51, 'Vitesse', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (304, 51, 'Relance', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (305, 51, 'Jeu aérien', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (306, 51, 'Anticipation', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (307, 52, 'Duel défensif', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (308, 52, 'Placement', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (309, 52, 'Vitesse', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (310, 52, 'Relance', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (311, 52, 'Jeu aérien', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (312, 52, 'Anticipation', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (313, 53, 'Qualité de passe', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (314, 53, 'Vision du jeu', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (315, 53, 'Technique', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (316, 53, 'Mobilité', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (317, 53, 'Pressing', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (318, 53, 'Endurance', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (319, 54, 'Qualité de passe', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (320, 54, 'Vision du jeu', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (321, 54, 'Technique', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (322, 54, 'Mobilité', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (323, 54, 'Pressing', 72);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (324, 54, 'Endurance', 76);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (325, 55, 'Finition', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (326, 55, 'Appels', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (327, 55, 'Vitesse', 90);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (328, 55, 'Technique', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (329, 55, 'Création', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (330, 55, 'Pressing', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (331, 56, 'Finition', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (332, 56, 'Appels', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (333, 56, 'Vitesse', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (334, 56, 'Technique', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (335, 56, 'Création', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (336, 56, 'Pressing', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (337, 57, 'Finition', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (338, 57, 'Appels', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (339, 57, 'Vitesse', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (340, 57, 'Technique', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (341, 57, 'Création', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (342, 57, 'Pressing', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (343, 58, 'Finition', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (344, 58, 'Appels', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (345, 58, 'Vitesse', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (346, 58, 'Technique', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (347, 58, 'Création', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (348, 58, 'Pressing', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (349, 59, 'Duel défensif', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (350, 59, 'Placement', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (351, 59, 'Vitesse', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (352, 59, 'Relance', 86);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (353, 59, 'Jeu aérien', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (354, 59, 'Anticipation', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (355, 60, 'Duel défensif', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (356, 60, 'Placement', 80);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (357, 60, 'Vitesse', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (358, 60, 'Relance', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (359, 60, 'Jeu aérien', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (360, 60, 'Anticipation', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (361, 61, 'Qualité de passe', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (362, 61, 'Vision du jeu', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (363, 61, 'Technique', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (364, 61, 'Mobilité', 79);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (365, 61, 'Pressing', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (366, 61, 'Endurance', 81);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (367, 62, 'Qualité de passe', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (368, 62, 'Vision du jeu', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (369, 62, 'Technique', 83);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (370, 62, 'Mobilité', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (371, 62, 'Pressing', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (372, 62, 'Endurance', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (373, 63, 'Finition', 84);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (374, 63, 'Appels', 77);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (375, 63, 'Vitesse', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (376, 63, 'Technique', 82);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (377, 63, 'Création', 75);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (378, 63, 'Pressing', 78);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (379, 64, 'Qualité de passe', 89);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (380, 64, 'Vision du jeu', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (381, 64, 'Technique', 88);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (382, 64, 'Mobilité', 87);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (383, 64, 'Pressing', 85);
INSERT INTO note_critere (id, rapport_id, critere, note_sur_100) VALUES (384, 64, 'Endurance', 85);
SELECT setval(pg_get_serial_sequence('note_critere','id'), (SELECT MAX(id) FROM note_critere));
COMMIT;
